name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: setup .env
        run: echo "${{ secrets.DOTENV }}" > .env

      - name: npm install
        run: npm install

      - name: run test
        run: node index.js

      - name: Upload screenshot debug
        uses: actions/upload-artifact@v2
        with:
          name: screenshot
          path: screenshot.png
          retention-days: 7
